<?php

$array = [ "TRAVAUX ISOLATION INTERIEURE", "TRAVAUX TRAITEMENT DE TOITURE", "TRAVAUX DE VENTILATION", "TRAVAUX D'ASSAINISSEMENT DE CHARPENTE", "TRAVAUX DE ZINGUERIE" ];

echo json_encode($array);

?>